# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe8fde1f840be184ae1ef0cc8e33c6baab3d798ffc4e20dbcea383865f6c3964c025bbd6290aa9bf82ec9f0d8f49eef5054759756f4250c73d9f1ca320432d49

test:
  secret_key_base: ffa69ed60b629bbe9442773b1811f793b3b387490112e508ab03bac3c1fb6d9cdc402ca35b58fd9c191689d3f7ef1ca81b9a41d210edcea1e7c50e85bdb6feef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
